### ISSUE TITLE
Support for span subviews

### ISSUE THREAD

**Issue by jdumas** [mosra/magnum-singles#2]
Hi,

Would you consider adding subviews (first/last/subspan) to CorradeArrayView.h for STL compatibility?

**Comment by mosra** [comment]
Hi, the functionality is already there, and I'd admit it offers even broader possibilities than STL: https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1ArrayView.html#Containers-ArrayView-usage-slicing

Or ... you mean like under the exact same name as in STL span?

**Comment by mosra** [comment]
PIMPL is the [Pointer](https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1Pointer.html) :) No custom deleter support, no `shared_ptr` equivalent, as simple as possible to cover exactly this case.

**Comment by mosra** [comment]
Ah, that would be a whole other thing. Here I have a policy that if a class needs to allocate something on a copy, then it should be move-only instead ... except for strings. So far that goes fine, `Pointer` is movable. But also I have a crazy specific use case where I can afford such restrictions, general-purpose code often can't.
